language: node_js
node_js:
- 11.11.0
before_script:
  export NODE_OPTIONS=–max_old_space_size=4096
script:
- npm i
- cd client
- npm i
- npm run build
- cd ..
- npm run build:server
- npm run test
after_script:
- rimraf node_modules
- rimraf node_modules --prefix client
deploy:
  provider: heroku
  api_key:
    secure: S43azm6JZ3v7SR20y+b82G6BD7qA0Hkpy8VVYPhOWK+NPKD28t53wriaZh6TQnjrLZcS6QGr/n0efgVyAi/tv0aaeRfk9qF0E9jStGJyNC7ilJal6rDjwBQBhpZzU6qlddJ9SUXXrBwJ+N14ZX89TlEZcnpZqY6LVpCrhwGqYUR1onzZu72t3vqqBbQTorRQaeL1aPc5HxfnG43KWzHfx7Gcues5orycV5g08xjHw6X0U9EYCw+UDqI87GcpG8alWB3QB0c74D+0xAawvBw2HlKMK+a1MM4ICEKA0pb5E4Gl2jvesCPvA7FJRnW6Upa22YrZP6rnKBkRy0i6DEYPOl4+j4TRl0lUvVDYaS8ic1BR/B62bldKWBDTjRfKCE1H/eGWkJTk/pEbnO3eKsNN0HhKOKUCjyUg7C8sUS1stypuiJ6/uKkGy2WKjI1l4RqDEX7+XGA+PMG7ezMcYzUWHfieGslvlFkpHsPqrcuOWcz2NLTa2DoxJY5EDm0g4/9/W1hFrzsCxXsEBJ7LyJaZa8grS/+idZRJq0fvx1veIDcTA/gKqnkmw3RV93KbHoEksaKrzoubawNQ5HLNY7YqYHAzWbHGf4FL8SAitndin4KB7yThVwO2oqAvwXFOFUt1aE3zw45xCOgVpg9dpPXrnX5pPttNgzYx30/RnM2YZsY=
  app:
    master: wilderlist-prod
    develop: wilderlist-dev
  on:
    repo: wsoeltz/wilderlist
  skip_cleanup: 'true'
