language: node_js
node_js:
- 11.11.0
before_install:
- openssl aes-256-cbc -K $encrypted_1b7c481f9230_key -iv $encrypted_1b7c481f9230_iv
  -in wilderlist-prod-ed3a9675b228.json.enc -out wilderlist-prod-ed3a9675b228.json
  -d
script:
- npm i
- cd client
- npm i
- npm run build
- cd ..
- npm run build:server
- npm run test
after_script:
- rimraf node_modules
- rimraf node_modules --prefix client
deploy:
- provider: heroku
  api_key:
    secure: BW//VwzGeIgz7bBIhHE8rut4Mfhz0o59xDOPWErCc2JZYAoW593wLYW2INBtaxK1akM+8jX3u/ehb02kVoRU94RR7fAb850mzvE2j0UsNdo7fp3/Zx4dwDOtkX3sENh/cfyHQf5NWX/JO2UZA11HrPuXhdYgjHvsgROsMFj/nDYkjxhRxzwM/L3O2CE+ZiJ7aJZcfsvfKVcr4IerCR5wsxcHSrYDQ0GBVlf46Grv7vEFsUBrwlZYiytYwHSKvhsS5TJ7isUaTA6gASqxDBSHMnhHWZXseH5tFwtqgpA5Eb2GKW8Fc/+idXZIbYlB34GwAaWXfYiq5a5VZHFCgqGD/5BmInCC4QR0UlTAH1qiAWU/yI/UmvtoFBF+RI0ubmZ/dlwh8rn43/Y1SX02t5QgmvYCXD1czXSFH4BlOV8+7zoUzjiNTzfClU6gX4LRzNW2B6AbGAyX4b+MyG/jGSmHVX9K03ry4EytJTXPFUrBP7bCRyVTDzvvsC1D16G84bCKEJ5ZYF8gksW5/Vwckr+xySGc4qJ4qm1SGN16hmTAImT42c3I2EHcRM9dasGAIpmpADJDu+0xe+dv2+4/dphha5mHSUzXWuUUnWGqWycBdlvAa6G2/oUhPFZA8hbnVyR3pS663VeGbJriUT0tXksdQhkkh2rO0ufuluo5RF+AfHE=
  skip_cleanup: true
  app: wilderlist-dev
  on:
    branch: develop
- provider: gae
  keyfile: wilderlist-prod-ed3a9675b228.json
  project: wilderlist-prod
  on:
    branch: master
