language: nodejs
before_script:
- npm run build
script:
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: MtSquWz1lqBOsEhjzFO5bnUAiZAHQKdzJ0GSssyswt2zG1kSj3AElZJOi/SGDjprguq2i0oWM/n4lzDXncM4QinpmUK/A2wpgt+Is2lbCMVUKpQ7SjaSnoxJwl8Okn+oxLeBC+PsgzpQxrtXWQt1nq3JTQLZN4NicAeazYdqZLKT2OrPV2PtBehmhhDWWv5uDHMhg5dSWjeXrLjs0XrDLAv0HWk0NdI6qA1zWOG5d2MdEWcxEPrL/g/QbF+cTeMsJQvXGz8XmD9uwniRMYaddh+hq9UC4dx/Ij09HPmTEMzxJFkiComqYD9J9vI9YF2P0C3CAJ8DWTUpp1HXSwAHUQ2suEq01okupT5+JESgRRxW2kpexHeuT49tZbRefwWJ4lPYIGyWEnLVcuoNYSZj0Hyekyfudko1rmjuAtSnpVAY6hkb6EFYu99CH0IFeNJCRk3ewnux9UEiR9MvYvusPZZEFP/sudzQmrbY5cKN0EKiOhS15IEaQDvxHwlbKnzviNZE/lJ5J/ZPWQ6dWHHlr/+4J+CffJTrJCktXbwuJOoHMMFlwVgXBpwWKxbfcu5ucDJobGMdPaX3CGYUS1VQ1Yq+SruYRhQ843wW5aSSEgfWE26WIZVbnLnemcVJAtyLlSLENeWKfEFF6FIxQBBmd1gPVz2RxHTCAQ1xoF43usk=
  skip_cleanup: true
  app: notches-hiking-lists
