export enum Routes {
  Login = '/',
  Dashboard = '/',
  Lists = '/lists',
  ListsWithDetail = '/lists/:id',
  ListDetail = '/list/:id',
  ListDetailWithMountainDetail = '/list/:id/mountain/:mountainId',
  MountainDetail = '/mountain/:id',
  Friends = '/users',
  FriendsWithProfile = '/users/:id',
  UserProfile = '/user/:id',
  ComparePeakList = '/user/:id/list/:peakListId',
  CompareAllPeaks = '/user/:id/compare-all-peaks',
  ComparePeakListIsolated = '/compare/user/:id/list/:peakListId',
  CompareAllPeaksIsolated = '/compare/user/:id/compare-all-peaks',
  Admin = '/admin',
  AdminRegions = '/admin/regions',
  AdminStates = '/admin/states',
  AdminMountains = '/admin/mountains',
  AdminPeakLists = '/admin/lists',
  AdminUsers = '/admin/users',
}
