export enum Routes {
  Login = '/',
  Dashboard = '/',
  Lists = '/lists',
  ListDetail = '/list/:id',
  MountainDetail = '/mountain/:id',
  Friends = '/users',
  UserProfile = '/user/:id',
  ComparePeakList = '/user/:friendId/list/:peakListId',
  CompareAllPeaks = '/user/:id/compare-all-peaks',
  Admin = '/admin',
  AdminRegions = '/admin/regions',
  AdminStates = '/admin/states',
  AdminMountains = '/admin/mountains',
  AdminPeakLists = '/admin/lists',
  AdminUsers = '/admin/users',
}
