export enum Routes {
  Login = '/',
  Dashboard = '/',
  DashboardWithPeakListDetail = '/dashboard/list/:peakListId',
  ListsWithDetail = '/lists/:id',
  ListDetail = '/list/:id',
  ListDetailWithMountainDetail = '/list/:id/mountain/:mountainId',
  MountainSearchWithDetail = '/mountains/:id',
  MountainDetail = '/mountain/:id',
  FriendsWithProfile = '/users/:id',
  UserProfile = '/user/:id',
  UserSettings = '/user-settings',
  OtherUserPeakList = '/user/:id/list/:peakListId',
  OtherUserPeakListDetail = '/detail/user/:friendId/list/:peakListId',
  OtherUserPeakListCompare = '/user/:id/compare/:peakListId',
  ComparePeakListWithMountainDetail = 'compare/user/:id/list/:peakListId/mountain/:mountainId',
  ComparePeakListIsolated = '/compare/user/:id/list/:peakListId',
  Admin = '/admin',
  AdminRegions = '/admin/regions',
  AdminStates = '/admin/states',
  AdminMountains = '/admin/mountains',
  AdminPeakLists = '/admin/lists',
  AdminUsers = '/admin/users',
  PrivacyPolicy = '/privacy-policy',
}
